version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - efiche-demo

  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - efiche-demo

  postgresql:
    container_name: efiche_postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nzabera2006
      POSTGRES_DB: efiche_challenge
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgresdb:/var/lib/postgresql/data
    networks:
      - efiche-demo
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d efiche_challenge -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  backup:
    image: eeshugerman/postgres-backup-s3:16
    environment:
      SCHEDULE: "0 0 * * *" # daily backup
      BACKUP_KEEP_DAYS: 7
      PASSPHRASE: passphrase
      S3_REGION: us-east-005
      S3_ACCESS_KEY_ID: 005f76a6497d8cb0000000002
      S3_SECRET_ACCESS_KEY: K0050HeVUPcaQ92g6bMt47K7ifd2SzQ
      S3_BUCKET: zibapay-db
      S3_PREFIX: backup
      POSTGRES_HOST: efiche_postgres
      POSTGRES_DATABASE: efiche_challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nzabera2006
      S3_ENDPOINT: https://s3.us-east-005.backblazeb2.com
    networks:
      - efiche-demo
    restart: unless-stopped
    depends_on:
      - postgresql

  efiche:
    container_name: efiche-challenge-api
    image: mikepn/efiche-backend-service:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 5050:5050
    networks:
      - efiche-demo
    depends_on:
      - postgresql
    environment:
      DATABASE_URL: "postgresql://postgres:nzabera2006@efiche_postgres:5432/efiche_challenge"
    env_file: ".env"
    restart: unless-stopped



  # pgadmin:
  #   container_name: ms_pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
  #     - ./backups:/backups
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - efiche-demo
  #   restart: unless-stopped
  #   depends_on:
  #     - postgresql

networks:
  efiche-demo:
    driver: bridge

volumes:
  postgresdb:
  pgadmin:
  portainer_data: